on:
  push:
    branches:
      - master
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 20
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          log-level: verbose
          server: ftp://ftp.sauln.co.za/public_html/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
